# Dockerfile.kafka
FROM confluentinc/cp-kafka:latest

# Install Python and pip
USER root
RUN if [ -f /etc/alpine-release ]; then \
      apk update && apk add --no-cache python3 py3-pip; \
    else \
      apt-get update && apt-get install -y python3 python3-pip; \
    fi

# Install necessary Python libraries
RUN pip3 install kafka-python pandas

# Copy the producer code and dataset
COPY kafka-producer /kafka-producer

# Set the working directory
WORKDIR /kafka-producer
